name: control all workflows

on:
  push:
    branches: [dev, main]
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  security-events: write
  packages: write

jobs:
  code-scan:
    uses: ./.github/workflows/ci-code-scan.yml

  secret-scan:
    uses: ./.github/workflows/ci-secrets-scan.yml
    secrets: inherit

  dependency-scan:
    uses: ./.github/workflows/ci-dependency-scan.yml

  hadolint-scan:
    uses: ./.github/workflows/ci-hadolint-scan.yml

  build-trivyscan-push:
    needs: [code-scan, secret-scan, dependency-scan, hadolint-scan]
    uses: ./.github/workflows/ci-build-push.yml
    secrets: inherit